version: "3.8"
services:
  mongodb:
    image: "mongo:4.4.6"
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - default
      - db_network
  mongo-express:
    image: "mongo-express:0.54.0"
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - default
  redis:
    image: "redis:6.2.4-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - db_network
  nginx:
    image: "nginx:1.21.1-alpine"
    container_name: "nginx"
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always
    networks:
      - route_network
  standings:
    image: standings
    container_name: standings
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    networks:
      - db_network
      - route_network
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
  db_network: {}
  route_network: {}